config/routes.rb
Rails.application.routes.draw do
  resources :mathvideos
  resources :chemistries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chemistry.rb
class Chemistry < ApplicationRecord
    has_one_attached :clip
    has_one_attached :thumbnail
end

app/models/mathvideo.rb
class Mathvideo < ApplicationRecord
    has_one_attached :clip
    has_one_attached :thumbnail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chemistries_controller.rb
class ChemistriesController < ApplicationController
  before_action :set_chemistry, only: %i[ show edit update destroy ]

  # GET /chemistries or /chemistries.json
  def index
    @chemistries = Chemistry.all
  end

  # GET /chemistries/1 or /chemistries/1.json
  def show
  end

  # GET /chemistries/new
  def new
    @chemistry = Chemistry.new
  end

  # GET /chemistries/1/edit
  def edit
  end

  # POST /chemistries or /chemistries.json
  def create
    @chemistry = Chemistry.new(chemistry_params)

    respond_to do |format|
      if @chemistry.save
        format.html { redirect_to chemistry_url(@chemistry), notice: "Chemistry was successfully created." }
        format.json { render :show, status: :created, location: @chemistry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chemistry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chemistries/1 or /chemistries/1.json
  def update
    respond_to do |format|
      if @chemistry.update(chemistry_params)
        format.html { redirect_to chemistry_url(@chemistry), notice: "Chemistry was successfully updated." }
        format.json { render :show, status: :ok, location: @chemistry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chemistry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chemistries/1 or /chemistries/1.json
  def destroy
    @chemistry.destroy

    respond_to do |format|
      format.html { redirect_to chemistries_url, notice: "Chemistry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chemistry
      @chemistry = Chemistry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chemistry_params
      params.require(:chemistry).permit(:title, :description, :clip, :thumbnail)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/mathvideos_controller.rb
class MathvideosController < ApplicationController
  before_action :set_mathvideo, only: %i[ show edit update destroy ]

  # GET /mathvideos or /mathvideos.json
  def index
    @mathvideos = Mathvideo.all
  end

  # GET /mathvideos/1 or /mathvideos/1.json
  def show
  end

  # GET /mathvideos/new
  def new
    @mathvideo = Mathvideo.new
  end

  # GET /mathvideos/1/edit
  def edit
  end

  # POST /mathvideos or /mathvideos.json
  def create
    @mathvideo = Mathvideo.new(mathvideo_params)

    respond_to do |format|
      if @mathvideo.save
        format.html { redirect_to mathvideo_url(@mathvideo), notice: "Mathvideo was successfully created." }
        format.json { render :show, status: :created, location: @mathvideo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mathvideo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mathvideos/1 or /mathvideos/1.json
  def update
    respond_to do |format|
      if @mathvideo.update(mathvideo_params)
        format.html { redirect_to mathvideo_url(@mathvideo), notice: "Mathvideo was successfully updated." }
        format.json { render :show, status: :ok, location: @mathvideo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mathvideo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mathvideos/1 or /mathvideos/1.json
  def destroy
    @mathvideo.destroy

    respond_to do |format|
      format.html { redirect_to mathvideos_url, notice: "Mathvideo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mathvideo
      @mathvideo = Mathvideo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mathvideo_params
      params.require(:mathvideo).permit(:title, :description, :clip, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemistries_helper.rb
module ChemistriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mathvideos_helper.rb
module MathvideosHelper
end

app/views/chemistries/_chemistry.html.erb
<div class="container">
  <div class="row justify-content-center">
      <% @chemistries.each do |chemistry| %>
      <div class="col-lg-4 mt-3">
        <div id="<%= dom_id chemistry %>">
          <div class="card text-center">
            <div class="card-header">
              <strong>Title:</strong>
              <%= chemistry.title %>
            </div>
            <div class="card-body">
              <h5 class="card-title"> Lectur 01</h5>
              <%= link_to chemistry.title, chemistry, class: "btn btn-primary" %>
              <p>
                <strong>Description:</strong>
                <%= chemistry.description %>
              </p>
              <p>
                <%= link_to "Show this video", chemistry, class: "btn btn-success" %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/chemistries/_form.html.erb
<%= form_with(model: chemistry) do |form| %>
  <% if chemistry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chemistry.errors.count, "error") %> prohibited this chemistry from being saved:</h2>

      <ul>
        <% chemistry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :clip%>
    <%= form.file_field :clip%>
  </div>
  <div>
    <%= form.label :thumbnail%>
    <%= form.file_field :thumbnail%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chemistries/edit.html.erb
<h1>Editing chemistry</h1>

<%= render "form", chemistry: @chemistry %>

<br>

<div>
  <%= link_to "Show this chemistry", @chemistry %> |
  <%= link_to "Back to chemistries", chemistries_path %>
</div>

app/views/chemistries/index.html.erb
<body class="signbody" id="bkngbody"> 
  <div class="col-lg-12">
    <h3 class="mt-3 mb-3 text-center"> Chemistry Videos</h3>
    <%= render "chemistry" %>
  </div>
</body>

app/views/chemistries/new.html.erb
<h1>Add Chemistry Videos</h1>

<%= render "form", chemistry: @chemistry %>

<br>

<div>
  <%= link_to "Back to chemistries", chemistries_path %>
</div>

app/views/chemistries/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="<%= dom_id @chemistry %>">
  <div class="container">
    <div class="card text-center">
      <div class="card-header">
        <strong>Title:</strong>
        <%= @chemistry.title %>
      </div>
      <div class="card-body">
        <h5 class="card-title"> Get ready with a pen and paper, and make sure you're able to focus before starting your study session</h5>
        <video
        id="my-video"
        class="video-js"
        controls
        preload="auto"
        width="640"
        height="264"
        poster="<%= url_for(@chemistry.thumbnail)%>"
        data-setup="{}"
      >
        <source src="<%= url_for(@chemistry.clip)%>" type="video/mp4" />
    
      </video>
      <p>
        <strong>Description:</strong>
        <%= @chemistry.description %>
      </p>
    
      </div>
    </div>
  </div>
</div>

   

<div class="text-center mt-3">
  <%= link_to "Back to all chemistry videos!", chemistries_path, class:"btn btn-primary mb-3" %>
  <%= link_to "Back to Home Page", root_path, class:"btn btn-success mb-3" %>
  <%= button_to "Destroy this video", @chemistry, method: :delete %>
</div>

app/views/home/index.html.erb
<body class="home-page" id="homebody">
  <div class="container text-center mt-2">
      <a href="https://www.iitcircuit.com/z", class="cta", style="float: left;">Physics</a>
      <%= link_to "Mathematics", mathvideos_path, class: "cta"%>
      <%= link_to "Chemistry", chemistries_path, class: "cta", style: "float: right;"%>
  </div>
  <div class="container text-center mt-2" id="home-container" >
    <h1 class= "hhome" id="homehone">Dear Tannu,</h1>
    <p class= "phome" id="homep">Preparing for JEE Advanced is undoubtedly a challenging and demanding task, but it is also an opportunity for you to achieve great things and reach your full potential. You have already taken the first step by choosing to pursue this path, and that in itself is commendable.
    </p>
    <p class= "phome" id="homep">Remember that the road to success is not an easy one, but it is not impossible either. With hard work, dedication, and the right mindset, you can overcome any obstacle and achieve your goals.</p>
    <p class= "phome" id="homep">Take small steps every day towards your preparation, and stay consistent in your efforts. Set achievable goals for yourself, and celebrate each milestone that you achieve along the way. Don't compare yourself with others, but instead, focus on improving yourself every day.
    </p>
    <p class= "phome" id="homep">Also, make sure to take care of your physical and mental health, as this will have a significant impact on your performance. Get enough sleep, exercise regularly, and eat a healthy and balanced diet. Take breaks when needed, and don't hesitate to seek help if you feel overwhelmed.</p>
    <p class= "phome" id="homep">Lastly, remember that failure is a part of the learning process, and it is okay to make mistakes. Don't let setbacks discourage you, but instead, use them as an opportunity to learn and grow. Believe in yourself and your abilities, and stay motivated and positive throughout your preparation.</p>
    <p class= "phome" id="homep">You can do this, Tannu! Best of luck for your JEE Advanced preparation.</p>

  </div>
</body>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "JEE_Home", root_path, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Chemistry</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Mathematics</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Physics</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JEEWithIITCircuit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
    .navbar {
  font-weight: bold;
  background-color: #00000080 !important;
  background-repeat: no-repeat;
  background-position: center;
}
* {
  box-sizing: border-box;
}
.cta {
  padding: 10px 45px;
  text-decoration: none;
  font-family: "Poppins", sans-serif;
  font-size: 40px;
  color: white;
  background: #6225e6;
  transition: 1s;
  box-shadow: 6px 6px 0 black;
  transform: skewX(-15deg);
}

.cta:focus {
  outline: none;
}

.cta:hover {
  transition: 0.5s;
  box-shadow: 10px 10px 0 #fbc638;
}

.cta span:nth-child(2) {
  transition: 0.5s;
  margin-right: 0px;
}

.cta:hover span:nth-child(2) {
  transition: 0.5s;
  margin-right: 45px;
}

span {
  transform: skewX(15deg);
}

span:nth-child(2) {
  width: 20px;
  margin-left: 30px;
  position: relative;
  top: 12%;
}

#homebody {
  background-image: url("https://img.etimg.com/thumb/width-1200,height-900,imgsize-153904,resizemode-1,msid-95301357/industry/services/education/iit-delhi-expands-its-campus-new-curriculum-and-abu-dhabi-campus-on-cards.jpg");
  background-size: cover;
  background-position: center;
  height: 100vh;
  width: 100%;
}
#home-container {
  padding: 20px;
  background-color: rgba(0, 0, 0, 0.5);
  border-radius: 20px;
}
#homehone {
  font-size: 36px;
  margin-top: 50px;
  margin-bottom: 20px;
  font-weight: bold;
  color: white !important;
}
#homep {
  font-size: 18px;
  margin-bottom: 40px;
  font-weight: bold;
  color: white !important;
}
    </style>

  </head>

  <body>
    <%= render partial: "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/mathvideos/_form.html.erb
<%= form_with(model: mathvideo) do |form| %>
  <% if mathvideo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mathvideo.errors.count, "error") %> prohibited this mathvideo from being saved:</h2>

      <ul>
        <% mathvideo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :clip%>
    <%= form.file_field :clip%>
  </div>
  
  <div>
    <%= form.label :thumbnail%>
    <%= form.file_field :thumbnail%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mathvideos/_mathvideo.html.erb
<div class="container">
  <div class="row justify-content-center">
      <% @mathvideos.each do |mathvideo| %>
      <div class="col-lg-4 mt-3">
        <div id="<%= dom_id mathvideo %>">
          <div class="card text-center">
            <div class="card-header">
              <strong>Title:</strong>
              <%= mathvideo.title %>
            </div>
            <div class="card-body">
              <h5 class="card-title"> Lectur 01</h5>
              <%= link_to mathvideo.title, mathvideo, class: "btn btn-primary" %>
              <p>
                <strong>Description:</strong>
                <%= mathvideo.description %>
              </p>
              <p>
                <%= link_to "Show this video", mathvideo, class: "btn btn-success" %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/mathvideos/edit.html.erb
<h1>Editing mathvideo</h1>

<%= render "form", mathvideo: @mathvideo %>

<br>

<div>
  <%= link_to "Show this mathvideo", @mathvideo %> |
  <%= link_to "Back to mathvideos", mathvideos_path %>
</div>

app/views/mathvideos/index.html.erb
<body class="signbody" id="bkngbody"> 
  <div class="col-lg-12">
    <h3 class="mt-3 mb-3 text-center"> Mathematics Videos</h3>
    <%= render "mathvideo" %>
  </div>
</body>

app/views/mathvideos/new.html.erb
<h1>Add Mathematics Videos</h1>

<%= render "form", mathvideo: @mathvideo %>

<br>

<div>
  <%= link_to "Back to mathvideos", mathvideos_path %>
</div>

app/views/mathvideos/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="<%= dom_id @mathvideo %>">
<div class="container">
<div class="card text-center">
  <div class="card-header">
    <strong>Title:</strong>
    <%= @mathvideo.title %>
  </div>
  <div class="card-body">
    <h5 class="card-title"> Get ready with a pen and paper, and make sure you're able to focus before starting your study session</h5>
    <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="640"
    height="264"
    poster="<%= url_for(@mathvideo.thumbnail)%>"
    data-setup="{}"
  >
    <source src="<%= url_for(@mathvideo.clip)%>" type="video/mp4" />

  </video>
  <p>
    <strong>Description:</strong>
    <%= @mathvideo.description %>
  </p>

  </div>
</div>
</div>
</div>

   

<div class="text-center mt-3">
  <%= link_to "Back to all mathematics videos", mathvideos_path, class: "btn btn-primary mb-3" %>
  <%= link_to "Back to Home Page", root_path, class: "btn btn-success mb-3" %>
  <%= button_to "Destroy this video", @mathvideo, method: :delete  %>
</div>